import { dev } from '$app/environment'
import {
	DATABASE_URL,
	DATABASE_AUTH_TOKEN,
	BETTER_AUTH_SECRET,
	BETTER_AUTH_URL,
	COOKIE_DOMAIN,
	DISCORD_CLIENT_SECRET,
	OTHER_TRUSTED_ORIGINS
} from '$env/static/private'
import { PUBLIC_DISCORD_APP_ID, PUBLIC_SESSION_SERVER_ORIGIN } from '$env/static/public'
import { getAuthServer, getDB } from 'shared'

export const auth = getAuthServer(
	getDB({ DATABASE_URL, DATABASE_AUTH_TOKEN }),
	{
		BETTER_AUTH_SECRET,
		BETTER_AUTH_URL,
		COOKIE_DOMAIN,
		DISCORD_CLIENT_SECRET,
		PUBLIC_DISCORD_APP_ID,
		PUBLIC_SESSION_SERVER_ORIGIN,
		OTHER_TRUSTED_ORIGINS
	},
	dev
)
