name: Quality Check
run-name: Checking commit by ${{ github.actor }}

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.15

      - name: Install dependencies
        run: bun i

      - name: Build
        run: bun run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
          BETTER_AUTH_URL: ${{ env.BETTER_AUTH_URL }}
          COOKIE_DOMAIN: ${{ env.COOKIE_DOMAIN }}
          PUBLIC_DISCORD_APP_ID: ${{ env.PUBLIC_DISCORD_APP_ID }}
          PUBLIC_SESSION_SERVER_ORIGIN: ${{ env.PUBLIC_SESSION_SERVER_ORIGIN }}
          OTHER_TRUSTED_ORIGINS: ${{ env.OTHER_TRUSTED_ORIGINS }}

      - name: Deploy Frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --cwd packages/sveltekit

      - name: Deploy Backend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --cwd packages/worker
